### ISSUE TITLE
KeyError: '3R3CSYCwXTmBW' 

### ISSUE THREAD

**Issue by zhuhongyue** [yalesong/pvse#11]
When I run python eval.py --data_name mrw --num_embeds 1 --img_attention --txt_attention --max_video_length 4 --ckpt ./ckpt/mrw_pvse_k1.pth. Something wrong occured. 
```
(pvse) zhyue@server-55:~/pvse$ python eval.py --data_name mrw --num_embeds 1 --img_attention --txt_attention --max_video_length 4 --ckpt ./ckpt/mrw_pvse_k1.pth
Loading dataset
Computing results... (eval_on_gpu=False)
Traceback (most recent call last):
  File "eval.py", line 290, in <module>
    metrics = evalrank(model, args, split='test')
  File "eval.py", line 214, in evalrank
    img_embs, txt_embs = encode_data(model, data_loader, args.eval_on_gpu)
  File "eval.py", line 28, in encode_data
    for i, data in enumerate(data_loader):
  File "/home/zhyue/anaconda2/envs/pvse/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zhyue/anaconda2/envs/pvse/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/zhyue/anaconda2/envs/pvse/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhyue/anaconda2/envs/pvse/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhyue/pvse/data.py", line 211, in __getitem__
    frames, meta = self.gulp[self.ids[index], start_idx:end_idx:skip]
  File "/home/zhyue/anaconda2/envs/pvse/lib/python3.7/site-packages/gulpio/fileio.py", line 135, in __getitem__
    chunk_id = self.chunk_lookup[id_]
KeyError: '3R3CSYCwXTmBW'
```

Any suggestion?

**Comment by yalesong** [comment]
The error says it cannot find a video file. Did you gulp the data yourself or download our pre-compiled version?

**Comment by zhuhongyue** [comment]
> The error says it cannot find a video file. Did you gulp the data yourself or download our pre-compiled version?

I already run 
`bash prepare_mrw_dataset.sh` for downloading your precompiled dataset.
and then got files in ./data/mrw and ./vocab/ as follow:
```
(pvse) zhyue@server-55:~/pvse/vocab$ ls
mrw_vocab.pkl  
(pvse) zhyue@server-55:~/pvse/data$ cd mrw/
(pvse) zhyue@server-55:~/pvse/data/mrw$ ls
mrw-v1.0.json  split
(pvse) zhyue@server-55:~/pvse/data/mrw$ cd split/
(pvse) zhyue@server-55:~/pvse/data/mrw/split$ ls
test.tsv  train.tsv  valid.tsv

**Comment by zhuhongyue** [comment]
Still need mrw/gulp data for run eval command

**Comment by yalesong** [comment]
Looks like you are trying to download videos and gulp them yourself. Why don't you try our precompiled gulpio data first? This is a recommended way for most people, it will be the easiest way to get started.

**Comment by yalesong** [comment]
Closing due to inactivity.
