### ISSUE TITLE
problems in mrw and tgif data set

### ISSUE THREAD

**Issue by pwy-cmd** [yalesong/pvse#6]
The following problems occurred when I used the mrw and tgif data set. How can I solve them?
mrw:I:\Python3.6\python.exe "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py"
Loading dataset
Computing results... (eval_on_gpu=False)
Traceback (most recent call last):
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 290, in <module>
    metrics = evalrank(model, args, split='test')
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 214, in evalrank
    img_embs, txt_embs = encode_data(model, data_loader, args.eval_on_gpu)
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 28, in encode_data
    for i, data in enumerate(data_loader):
  File "I:\Python3.6\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "I:\Python3.6\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "I:\Python3.6\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "M:\HJH\Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval\pvse-master\data.py", line 211, in __getitem__
    frames, meta = self.gulp[self.ids[index], start_idx:end_idx:skip]
  File "I:\Python3.6\lib\site-packages\gulpio\fileio.py", line 135, in __getitem__
    chunk_id = self.chunk_lookup[id_]
KeyError: '3R3CSYCwXTmBW'

Process finished with exit code 1

tgif:I:\Python3.6\python.exe "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py"
Loading dataset
Computing results... (eval_on_gpu=False)
Traceback (most recent call last):
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 290, in <module>
    metrics = evalrank(model, args, split='test')
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 214, in evalrank
    img_embs, txt_embs = encode_data(model, data_loader, args.eval_on_gpu)
  File "M:/HJH/Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval/pvse-master/eval.py", line 28, in encode_data
    for i, data in enumerate(data_loader):
  File "I:\Python3.6\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "I:\Python3.6\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "I:\Python3.6\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "I:\Python3.6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "M:\HJH\Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval\pvse-master\data.py", line 296, in __getitem__
    frames, meta = self.gulp[self.ids[index], start_idx:end_idx:skip]
  File "I:\Python3.6\lib\site-packages\gulpio\fileio.py", line 135, in __getitem__
    chunk_id = self.chunk_lookup[id_]
KeyError: 'tumblr_n9n04znLpA1qddk8uo1_500'

Process finished with exit code 1

**Comment by yalesong** [comment]
It's complaining that the process cannot find the files (3R3CSYCwXTmBW for MRW and tumblr_n9n04znLpA1qddk8uo1_500 for TGIF). Did you download pre-gulped data or download video files and gulped them yourself? If the former, make sure they the directory setting is correct.

**Comment by pwy-cmd** [comment]
I am using the pre-compiled GulpIO data you provided.
This link for mrw dataset (54 GB)(https://drive.google.com/file/d/14hni_L2iN3_zsZ1KDkh21juWYCE0s13j),
and this link for tgif dataset(89 GB)(https://drive.google.com/file/d/1W2iXV9tWxKkYkTzOCvUMTQBkVPg_8mOf)
After finish downloading, I extract the tarball under `data/mrw/gulp` to run the program.
I also put the split file in mrw and tgif or gulp,but it still complaining that the process cannot find the files (3R3CSYCwXTmBW for MRW and tumblr_n9n04znLpA1qddk8uo1_500 for TGIF).
I want to know if my path is wrong or the wrong is due to other problems.
Thank you very much for you patient reply!

**Comment by pwy-cmd** [comment]
I am using the pre-compiled GulpIO data you provided.
This link for mrw dataset (54 GB)(https://drive.google.com/file/d/14hni_L2iN3_zsZ1KDkh21juWYCE0s13j),
and this link for tgif dataset(89 GB)(https://drive.google.com/file/d/1W2iXV9tWxKkYkTzOCvUMTQBkVPg_8mOf)
After finish downloading, I extract the tarball under `data/mrw/gulp` to run the program.
I also put the split file in mrw and tgif or gulp,but it still complaining that the process cannot find the files (3R3CSYCwXTmBW for MRW and tumblr_n9n04znLpA1qddk8uo1_500 for TGIF).
I want to know if my path is wrong or the wrong is due to other problems.
Thank you very much for you patient reply!

**Comment by yalesong** [comment]
Closing due to inactivity. Feel free to bring it back if there's any development.
